CREATE TABLE Narachka(
    ID INT PRIMARY KEY,
    marketID INT REFERENCES Market(ID) ON DELETE SET NULL ON UPDATE CASCADE,
    specijalitetKod INT REFERENCES Specijalitet(ID) ON DELETE SET NULL ON UPDATE CASCADE,
    korisnikID INT REFERENCES Korisnik(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    datum DATE CHECK(datum >= '2010-10-20'),
);