 CREATE TABLE S(C INT PRIMARY KEY, D INT);
 CREATE TABLE R(A INT PRIMARY KEY, B INT FOREIGN KEY REFERENCES S(C) ON DELETE CASCADE ON UPDATE CASCADE);

INSERT INTO S VALUES (2, 10), (3, 11), (4, 12), (5, 13);
SELECT * FROM S;

INSERT INTO R VALUES (0, 4), (1, 5), (2, 4), (3, 5);
SELECT * FROM R;

SELECT * FROM S 

DELETE FROM S WHERE C=4
SELECT * FROM S
SELECT * FROM R

UPDATE R SET A=20 WHERE A=1
SELECT * FROM R 

DROP TABLE S (ili R)